### ISSUE TITLE
TMP: Tabs get re-ordered on tab unload

### ISSUE THREAD

**Issue by Gurtz** [philikon/BarTab#39]
For some reason, when I unload a tab using the right-click menu, the tab is unloaded ... but it also moves one tab to the right. It seems it should leave the tab ordering unchanged.

That aside, fantastic add-on! Thank you so much for all the effort!

**Comment by philikon** [comment]
Indeed, you're right, the tab should remain in its place. If we knew what caused this, we could track it down better and possibly fix it.

Are you using Tab Mix Plus or some other add-on to manipulate tab behaviour? I remember a user reporting the same problem and the reason was some setting in Tab Mix Plus. Changing that setting fixed it, IIRC.

**Comment by Gurtz** [comment]
Yes, I am using Tab Mix Plus. [At the moment, version 0.3.8.2.] 

If you have any thoughts on the setting that needs to change, that would be great. Thanks!

**Comment by philikon** [comment]
Ah yes, I found it in the archives: The problem only appears when you check the "Open other tabs next to current one" setting (corresponds to the 'extensions.tabmix.openTabNext' preference). If you uncheck that, it works normally.

I'm inclined not to do anything about this behaviour because Firefox 3.6 has the "open tabs next to the current one" feature out of the box, and this one is compatible with BarTab. My general policy is not to support the quirks of add-ons that duplicate features in Firefox.

**Comment by Gurtz** [comment]
Yes, that seems to be it. I tried disabling the option, hoping that the Firefox default behavior would take over (and put my tabs to the right of the open one) ... but it didn't, unfortunately. The TabMix Plus option seems to override Firefox. So, I either have to give up TabMix Plus (which I'd prefer not to do, since it allows multiple rows of tabs), or live with the tiny odd behavior with BarTab. I think I'll just live with the latter. It's not a big inconvenience, and I completely understand not wanting to make a change for a feature that is handled by default in Firefox. No worries. 

Thanks for the prompt feedback! And thanks again for BarTab -- which is literally the highlight of my week ... maybe the month :-)
