### ISSUE TITLE
1.6b3 Does nothing in Firefox 3.5.9

### ISSUE THREAD

**Issue by JohnAJimenez** [philikon/BarTab#40]
Upgraded from 1.5b1 which was working to 1.6b3 which is not and now there is no way for me to rollback. 1.5.1 was not working for me which is why I went with the beta.
Any way someone can mirror the 1.5b1 xpi?

**Comment by philikon** [comment]
Yes, the 1.6 betas don't work with Firefox 3.5.9 yet. I've fixed this already so that the next beta will work. You should be able to downgrade to 1.5.1 just fine, just go to https://addons.mozilla.org/firefox/addon/67651 and click on "Add to Firefox". There's very little difference between 1.5b1 and 1.5.1.
