### ISSUE TITLE
any way to get barebones support for Firefox-3.0?

### ISSUE THREAD

**Issue by rtsai** [philikon/BarTab#59]
I'd like the auto-unload/load functionality for Firefox-3.0 (Mac). It is my main development browser because Firebug runs so much slower in later versions. I don't care so much about the other features for this use case.

**Comment by philikon** [comment]
Nope, sorry. Going forward I will focus on Firefox 3.6 and 4. At this point only 10% of BarTab users are even running Firefox 3.5.

You should seriously consider upgrading to Firefox 3.6. Not only is it safer, but it's also a lot faster. I also bet that Firebug won't be as slow anymore as you claim it to be. Either way, you don't always have to run Firebug. I keep it in a separate profile so that my main browsing profile isn't slowed down by it.
